# Generated by Django 5.0.7 on 2024-07-25 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="записи",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пациент",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="diagnostic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="записи",
                to="main.diagnostic",
                verbose_name="диагностика",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="doctor",
            field=models.ManyToManyField(related_name="врач", to="main.doctor"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="записи",
                to="main.doctor",
                verbose_name="врач",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="speciality",
            field=models.ManyToManyField(
                related_name="speciality",
                to="main.speciality",
                verbose_name="Специализация",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="услуги",
                to="main.speciality",
                verbose_name="специализация",
            ),
        ),
    ]
